title:        Tyk API Managment
url:          http://tyk.management.apievangelist.com/
logo:         https://kinlane-productions.s3.amazonaws.com/api-evangelist/api-evangelist-logo-400.png
logo_width:   65
logo_bottom_padding: 10

slash: /

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 150
paginate_path: "/blog/page:num"

github_org: kinlane
github_repo: tyk-api-management

# Masthead title
masthead_link: http://tyk.management.apievangelist.com/
masthead_font_size: 90
masthead_title: '{"Tyk API Management"}'

# Feature
feature_title: API Guide
feature_link: http://apievangelist.com
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/api-guides-loading.jpg
feature_image_width: 45

# Project
project_image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-padlock.png
project_summary: This is my research to better understand, and hopefully define what it takes to secure APIs. This area is the biggest concern of companies looking to do APIs, but is one of the most deficient areas of the API life cycle. You can find news I've curated, organizations doing interesting things, some of the common building blocks I've identified, and open source tooling in this research report.

# Navigation
navigation:
  - label1: Home
    link1: /
    size1: 90
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 10
    decorate: 0
  - label1: Return to API Evangelist
    link1: http://apievangelist.com
    size1: 90
    extend: 0
    label2:
    link2:
    size2: 10
    padding: 0
    decorate: 1

# Footer Navigation
footernavigation:
  - label: API 100K View
    link: http://apievangelist.com
  - label: News
    link: /news/
  - label: Partners
    link: http://apievangelist.com/partners/
  - label: APIs.json
    link: http://apisjson.org
  - label: About Kin Lane
    link: http://kinlane.com
  - label: Branding Guidelines
    link: http://apievangelist.com/branding-guidelines.html
  - label: Contact
    link: http://kinlane.com/contacts/

# sponsors
sponsors_margin_top: 15
sponsors_padding_top: 3
sponsors_json_url: https://s3.amazonaws.com/kinlane-productions/json/sponsors.json

# Footer
footer_title: API Evangelist
footer_link: http://apievangelist.com
footer_image_source: https://s3.amazonaws.com/kinlane-productions/footer/empowered-by-you-banner.png
footer_image_width: 60

# curated
curated_desc: As I keep track on the world of APIs I curate news, blog posts, articles, and other research that I feel is relevant specifically to API security--these are the links I am including in my research.

# organizations
org_desc: As I keep track on the world of APIs and read through the information I am curating I keep an eye out for any company, institution, or other agency that is doing anything interesting with API security. These are the organizations I'm currently including in my API security research.

# tools
tools_desc: These are the open source management related tooling that I am tracking on as part of my research, and can be used as part of the API security process.
